services:
  - type: web
    name: groupme-bot
    env: python        # tells Render to use the Python runtime
    plan: free         # keeps you on the free tier

    # If you don’t need to compile anything, leave buildCommand blank:
    buildCommand: "pip install -r requirements.txt"

    # Gunicorn is recommended in production, but simple python works:
    startCommand: "python main.py"

    # If main.py listens on a port other than 8080, add:
    #   envVars:
    #     - key: PORT
    #       value: "8080"
